# Generated by Django 3.2.5 on 2021-12-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_number', models.CharField(max_length=2)),
                ('building_number', models.CharField(max_length=2)),
                ('faculty_number', models.CharField(max_length=2)),
                ('room_number', models.CharField(max_length=3)),
                ('item_number', models.CharField(max_length=3, unique=True)),
                ('description', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('rented', 'Rented'), ('pending', 'Pending'), ('available', 'Available'), ('missing', 'Missing')], default='available', max_length=30)),
            ],
        ),
    ]
