# Generated by Django 3.2.5 on 2021-12-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_itemrent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemrent',
            old_name='return_Date',
            new_name='return_date',
        ),
    ]
