# Generated by Django 3.2.5 on 2021-12-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20211227_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_rented',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_returned',
        ),
    ]
