# Generated by Django 3.2.5 on 2022-01-05 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0008_auto_20211227_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemrent',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
